import type { AppTheme } from "../types";

export const lavenderTheme: AppTheme = {
  id: "lavender",
  name: "Lavender Dream",
  isBuiltIn: true,
  colors: {
    surface: "#FEDFED",
    card: "#FFFFFF",
    elevated: "#F2E6F5",
    inputBg: "#FFF5FA",
    textBody: "#3D2B4F",
    textMuted: "#A890B0",
    textDim: "#C8B8D0",
    textOnAccent: "#FFFFFF",
    accent: "#8FA2D4",
    accentStrong: "#AD81BE",
    accentLight: "#D5B5EA",
    headerBg: "#8FA2D4",
    headerText: "#FFFFFF",
    border: "#EEE2F5",
    bubbleOwn: "#D5B5EA",
    bubbleOther: "#FFFFFF",
    success: "#95D1AA",
    warning: "#D4A85A",
    danger: "#E07070",
    whatsGreen: "#25D366",
    biological: { pee: "#D4A85A", poop: "#8B7355" },
    feeding: { bottle: "#95D1AA", breast: "#AD81BE" },
    growth: "#72A098",
  },
};
