#!/usr/bin/env node
/**
 * gen-sitemap.mjs
 *
 * Scans the app/ directory and generates a Mermaid flowchart + route table
 * for SITEMAP.md. Run with:
 *
 *   node scripts/gen-sitemap.mjs
 *
 * Output is written to stdout. Redirect to update SITEMAP.md:
 *
 *   node scripts/gen-sitemap.mjs > SITEMAP.md
 *
 * The script detects:
 *   - Route files from directory structure
 *   - Component names (export default function)
 *   - Navigation calls: router.push(), router.replace(), router.back()
 *   - useLocalSearchParams() for dynamic params
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const APP_DIR = path.join(ROOT, "app");

// ─── Helpers ────────────────────────────────────────────────────────────────

function toRoute(filePath) {
  const relative = path.relative(APP_DIR, filePath);
  let route = relative.replace(/\.tsx?$/, "").replace(/\\/g, "/");
  // index routes -> parent path
  if (route.endsWith("/index")) route = route.slice(0, -6);
  // [param] -> :param
  route = route.replace(/\[(\w+)\]/g, ":$1");
  return "/" + route;
}

function extractExports(filePath) {
  const src = fs.readFileSync(filePath, "utf-8");
  const lines = src.split("\n");

  // Component name: `export default function ComponentName`
  const componentMatch = src.match(/export default function\s+(\w+)/);
  const componentName = componentMatch ? componentMatch[1] : null;

  // Navigation calls: router.push("..."), router.push(`...${var}`), router.push({pathname: "..."})
  const pushes = [];
  const pushRe =
    /router\.(?:push|replace)\((?:\{[\s\S]*?pathname:\s*["'`]([^"'`]+)["'`][\s\S]*?\}|["'`]([^"'`]+?)["'`])\)/g;
  let m;
  while ((m = pushRe.exec(src)) !== null) {
    const target = m[1] || m[2];
    pushes.push(target);
  }

  // router.back() calls
  const backs = (src.match(/router\.back\(\)/g) || []).length;

  // useLocalSearchParams
  const paramsMatch = src.match(/useLocalSearchParams<\{([^}]+)\}>\(\)/);
  const params = paramsMatch
    ? paramsMatch[1].split(";").map((s) => s.trim().split(":")[0].trim())
    : [];

  return { componentName, pushes, backs, params };
}

function guessPurpose(componentName, route) {
  if (!componentName) return "";
  const map = {
    TimelineScreen: "Main feed with bubbles + quick actions",
    EventDetailScreen: "View/edit a timeline event",
    FeedingDetailScreen: "View/edit a feeding session",
    SleepDetailScreen: "View/edit a sleep session",
    DiaperNewScreen: "New diaper log",
    EventNewScreen: "Create a new event",
    FeedingRetroScreen: "Retroactive feeding entry",
    GrowthHistoryScreen: "Growth measurement history",
    GrowthNewScreen: "New growth measurement",
    SettingsScreen: "Settings list",
    ThemeSelectorScreen: "Theme list & selector",
    ThemeEditorScreen: "Create/edit custom theme",
    CatalogsScreen: "Customize event types & scales",
    BabyProfile: "Edit baby info",
    StatsScreen: "Charts & statistics",
    GenerateReport: "Share reports",
    Welcome: "Onboarding welcome",
    RoleSelection: "Select caregiver role",
    BabySetup: "Enter baby info",
  };
  return map[componentName] ?? "";
}

// ─── Main ───────────────────────────────────────────────────────────────────

function walkDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(full));
    } else if (
      entry.isFile() &&
      /\.tsx?$/.test(entry.name) &&
      !entry.name.endsWith(".bak")
    ) {
      files.push(full);
    }
  }
  return files;
}

const routeFiles = walkDir(APP_DIR).sort();
const routes = [];

for (const filePath of routeFiles) {
  const route = toRoute(filePath);
  const info = extractExports(filePath);
  routes.push({ filePath, route, ...info });
}

// ─── Output ──────────────────────────────────────────────────────────────────

console.log(`# SITEMAP — Cielo App`);
console.log(`\n> Auto-generated by \`node scripts/gen-sitemap.mjs\` on ${new Date().toISOString().slice(0, 10)}`);
console.log(`> ${routes.length} routes found. Run \`node scripts/gen-sitemap.mjs\` to regenerate.`);

// ─── Route Tree ──────────────────────────────────────────────────────────────

console.log(`\n## Route Tree`);
console.log("\n```");
function printTree(routes) {
  const tree = {};
  for (const r of routes) {
    const parts = r.route.split("/").filter(Boolean);
    let node = tree;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (!node[part]) node[part] = {};
      node = node[part];
      if (i === parts.length - 1) node._route = r;
    }
  }
  function printBranch(branch, indent) {
    const keys = Object.keys(branch).filter((k) => k !== "_route").sort();
    for (const key of keys) {
      const child = branch[key];
      const isFile = child._route && child._route.componentName;
      const marker = isFile ? ` (${child._route.componentName})` : "";
      console.log(`${indent}├── ${key}${marker}`);
      printBranch(child, indent + "│   ");
    }
  }
  printBranch(tree, "");
}
printTree(routes);
console.log("```");

// ─── Mermaid Diagram ─────────────────────────────────────────────────────────

console.log(`\n## Navigation Diagram`);
console.log("\n```mermaid");
console.log("flowchart TB");
console.log('  classDef entry fill:#FF8AB3,color:#fff,stroke:#FF5C9A,font-weight:bold');
console.log('  classDef screen fill:#FFF0F5,color:#333,stroke:#FFB7D5');
console.log('  classDef log fill:#FFE4EE,color:#333,stroke:#FFB7D5');
console.log('  classDef settings fill:#E8F4FD,color:#333,stroke:#90CAF9');

// Static diagram header
console.log('');
console.log('  Index["/ (index.tsx)<br/>Entry Point"]:::entry');
console.log('  Dashboard["/dashboard<br/>Main Timeline"]:::screen');

// Onboarding nodes
console.log('  subgraph Onboarding');
for (const r of routes) {
  if (r.route.startsWith("/onboarding")) {
    const label = r.route + (r.componentName ? `<br/>${r.componentName}` : "");
    console.log(`    ${id(r)}["${label}"]:::screen`);
  }
}
console.log('  end');

// Log nodes
console.log('  subgraph Logs');
for (const r of routes) {
  if (r.route.startsWith("/logs")) {
    const label = r.route + (r.componentName ? `<br/>${r.componentName}` : "");
    console.log(`    ${id(r)}["${label}"]:::log`);
  }
}
console.log('  end');

// Settings nodes
console.log('  subgraph Settings');
for (const r of routes) {
  if (
    r.route.startsWith("/settings") ||
    r.route === "/baby/profile"
  ) {
    const label = r.route + (r.componentName ? `<br/>${r.componentName}` : "");
    console.log(`    ${id(r)}["${label}"]:::settings`);
  }
}
console.log('  end');

// Other screens
const others = ["/stats", "/timeline", "/report/generate"];
console.log('  subgraph Other');
for (const r of routes) {
  if (others.includes(r.route)) {
    const label = r.route + (r.componentName ? `<br/>${r.componentName}` : "");
    console.log(`    ${id(r)}["${label}"]`);
  }
}
console.log('  end');

// Connections (simplified - based on router.push/replace extracts)
console.log('');
console.log('  Index -->|onboarding_done=false| Welcome');
console.log('  Index -->|onboarding_done=true| Dashboard');
console.log('  Welcome -->|router.push| Role');
console.log('  Role -->|router.push| Baby');
console.log('  Baby -->|router.replace| Dashboard');

for (const r of routes) {
  for (const target of r.pushes) {
    const targetRoute = routes.find(
      (rt) => rt.route === target || rt.route.endsWith(target.replace(/\/$/, ""))
    );
    if (targetRoute) {
      // Only show if it's a forward navigation (not to self)
      if (targetRoute.route !== r.route) {
        console.log(`  ${id(r)} -->|push| ${id(targetRoute)}`);
      }
    }
  }
}

console.log("```");

// ─── Route Table ─────────────────────────────────────────────────────────────

console.log(`\n## Route Table`);
console.log("\n| Route | Component | Purpose | Navigates To |");
console.log("|-------|-----------|---------|-------------|");

for (const r of routes) {
  const routeLink = `\`${r.route}\``;
  const comp = r.componentName ? `\`${r.componentName}\`` : "—";
  const purpose = guessPurpose(r.componentName, r.route) || "—";
  const targets =
    r.pushes.length > 0
      ? r.pushes
          .map((t) => `\`${t}\``)
          .filter((t) => !t.includes("${")) // skip dynamic templates
          .join(", ") || "—"
      : r.backs > 0
        ? "`router.back()`"
        : "—";
  console.log(`| ${routeLink} | ${comp} | ${purpose} | ${targets} |`);
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slug(route) {
  return route.replace(/[/:()]/g, "_").replace(/__+/g, "_").replace(/^_/, "").replace(/_$/, "") || "root";
}

function id(r) {
  return slug(r.route);
}
